source "https://rubygems.org"

# Match the GitHub Pages build environment.
gem "github-pages", "~> 232", group: :jekyll_plugins

# Additional plugins not provided by github-pages.
group :jekyll_plugins do
  gem "jekyll-admin"
  gem "jekyll-algolia"
end

gem "faraday-retry"
